### ISSUE TITLE
How can i add ToxProxy in my VPS? 

### ISSUE THREAD

**Issue by 44667788** [zoff99/ToxBlinkenwall_raspi_lite_image#3]
Hello, are there any way to add a ToxProxy in my VPS?

**Comment by zoff99** [comment]
you can, but you should not. since everybody who has access to your VPN will be able to read all messages.

you can either build it on linux:
https://github.com/zoff99/ToxProxy/blob/zoff99/tweaks_001/do_it_systemlibs.sh
or build and run inside docker:
https://github.com/zoff99/ToxProxy/blob/zoff99/tweaks_001/Dockerfile

**Comment by zoff99** [comment]
this is the wrong repo, please use https://github.com/zoff99/ToxProxy
for things regarding ToxProxy

**Comment by 44667788** [comment]
Get it!Thanks!
